import ply.lex as lex
import ply.yacc as yacc
import sys
from pathlib import Path

# Create a list to hold all of the token names
tokens = [

    'INT',
    'FLOAT',
    'NAME',
    'PLUS',
    'MINUS',
    'DIVIDE',
    'MULTIPLY',
    'EQUALS',
    'DRAW',
    'FOR',
    'OPEN',
    'CLOSE',
    'OPEN_P',
    'CLOSE_P',
    'SEMICOLON',
    'STRING',
    'Q_MARK',
    'PRINT'

]

# Use regular expressions to define what each token is
t_PLUS = r'\+'
t_MINUS = r'\-'
t_MULTIPLY = r'\*'
t_DIVIDE = r'\/'
t_EQUALS = r'\='
#t_DRAW = "DRAW"
#t_FOR = "FOR"
t_OPEN = r'\{'
t_CLOSE = r'\}'
t_OPEN_P = r'\('
t_CLOSE_P = r'\)'
t_SEMICOLON = r'\;'
t_Q_MARK = r"\""
#t_PRINT = "PRINT"

# Ply's special t_ignore variable allows us to define characters the lexer will ignore.
# We're ignoring spaces.
t_ignore = r' '

# More complicated tokens, such as tokens that are more than 1 character in length
# are defined using functions.
# A float is 1 or more numbers followed by a dot (.) followed by 1 or more numbers again.

def t_STRING(t):
    r'\"[a-zA-Z_][a-zA-Z_0-9]*\"'
    t.type = "STRING"
    t.value = str(t.value)
    return t;

def t_DRAW(t):
    "DRAW"
    t.type = "DRAW"
    return t

def t_FOR(t):
    "FOR"
    t.type = "FOR"
    return t

def t_PRINT(t):
    "PRINT"
    t.type = "PRINT"
    return t

def t_FLOAT(t):
    r'\d+\.\d+'
    t.value = float(t.value)
    return t

# An int is 1 or more numbers.
def t_INT(t):
    r'\d+'
    t.value = int(t.value)
    return t

# A NAME is a variable name. A variable can be 1 or more characters in length.
# The first character must be in the ranges a-z A-Z or be an underscore.
# Any character following the first character can be a-z A-Z 0-9 or an underscore.
def t_NAME(t):
    r'[a-zA-Z_][a-zA-Z_0-9]*'
    t.type = 'NAME'
    return t

# Skip the current token and output 'Illegal characters' using the special Ply t_error function.
def t_error(t):
    print("Illegal characters!")
    t.lexer.skip(1)

# Build the lexer
lexer = lex.lex()

# Ensure our parser understands the correct order of operations.
# The precedence variable is a special Ply variable.
precedence = (

    ('left', 'PLUS', 'MINUS'),
    ('left', 'MULTIPLY', 'DIVIDE'),

)

# Define our grammar. We allow expressions, var_assign's and empty's.


def p_gooooooooooo(p):
    '''
    run : expression
         | var_assign
         | empty
    '''
    print(run(p[1]))

def p_var_assign(p):
    '''
    var_assign : NAME EQUALS expression SEMICOLON
    '''
    # Build our tree
    p[0] = ('=', p[1], p[3])

# Expressions are recursive.
def p_expression(p):
    '''
    expression : expression MULTIPLY expression SEMICOLON
               | expression DIVIDE expression SEMICOLON
               | expression PLUS expression SEMICOLON
               | expression MINUS expression SEMICOLON
    '''
    # Build our tree.
    print((p[2], p[1], p[3]))
    p[0] = (p[2], p[1], p[3])

def p_expression_int_float(p):
    '''
    expression : INT
               | FLOAT
               | STRING
    '''
    p[0] = p[1]

def p_expression_var(p):
    '''
    expression : NAME
    '''
    p[0] = ('var', p[1])

def p_draw(p):
    '''
    expression : DRAW expression expression
    '''
    p[0] = (p[1], p[2], p[3])

def p_for(p):
    '''
    expression : FOR OPEN_P expression CLOSE_P OPEN expression CLOSE
    '''
    p[0] = ('FOR', p[2])

def p_print(p):
    '''
    expression : PRINT expression SEMICOLON
    '''
    p[0] = ('PRINT','print(\'{}\')'.format(p[2]))

# Output to the user that there is an error in the input as it doesn't conform to our grammar.
# p_error is another special Ply function.
def p_error(p):
    print("Syntax error found!")

def p_empty(p):
    '''
    empty :
    '''
    p[0] = None

# Build the parser
parser = yacc.yacc()
# Create the environment upon which we will store and retreive variables from.
env = {}
# The run function is our recursive function that 'walks' the tree generated by our parser.
def run(p):
    global env
    if type(p) == tuple:
        if p[0] == '+':
            compiled_lines.append('{}+{}'.format(p[1],p[2]))
            return #run(p[1]) + run(p[2])
        elif p[0] == '-':
            return run(p[1]) - run(p[2])
        elif p[0] == '*':
            return run(p[1]) * run(p[2])
        elif p[0] == '/':
            return run(p[1]) / run(p[2])
        elif p[0] == '=':
            env[p[1]] = run(p[2])
            return ''
        elif p[0] == 'var':
            if p[1] not in env:
                return 'Undeclared variable found!'
            else:
                return env[p[1]]
        elif p[0] == 'DRAW':
            print('DRAW LINE: X:', p[1], 'and Y:',p[2])
        elif p[0] == 'FOR':
            print('TEST: ',p[1])
        elif p[0] == 'PRINT':
            print(p[1])
    else:
        return p

# Create a REPL to provide a way to interface with our calculator.
# while True:
#     try:
#         s = input('')
#     except EOFError:
#         break
#     parser.parse(s)


p = Path('program.x')
lines = p.read_text().splitlines()
compiled_lines = []

for line in lines:
    parser.parse(line)

with open('program.py', 'a') as the_file:
    if not compiled_lines:
        print("error")
    else:
        first_lines ="""
from tkinter import *
master = Tk()
w = Canvas(master, width=1280, height=720)
w.pack()

w.create_line(0, 0, 1280, 720)
"""
        compiled_lines.insert(0, first_lines)

        compiled_lines.append("master.mainloop()")

        for line in compiled_lines:
            the_file.write(line+'\n')

